### PR TITLE
Don't set repository.

### PR DESCRIPTION
**Pull request by peteruhnak**
Minor change that removes `spec repository: 'filetree://repository/mc'.`, because this breaks down when the project is loaded from someone else's `ConfigurationOf`.

And merged in the `commandShell` method, because no point in having an extra method.

### CODE REVIEW

**Comment by estebanlm** [comment]
is ok, why did you remove #commandShell: method and merged it with baseline?
(and btw... we should deprecate configuration and make a baseline from this)

**Comment by peteruhnak** [comment]
Because it looks odd. I've never seen such appropach in any Baseline/Configuration so it appears confusing.
I can change it back if you want.

**Comment by estebanlm** [comment]
How so? *all* baselines I uses/working on *plus* the versioner template suggest this approach... and all the baselines I work on uses them.

**Comment by peteruhnak** [comment]
I've reverted that particular change. I've just never seen such approach, so I guess I have some studying to do. :)

**Pull request merged**
